#!/usr/bin/env node

const { Client } = require('pg');

const HELP = `An expense recording system

Commands:

add AMOUNT MEMO [DATE] - record a new expense
clear - delete all expenses
list - list all expenses
delete NUMBER - remove expense with id NUMBER
search QUERY - list expenses with a matching memo field`;

let client = new Client({ database: 'expenses' });

async function listExpenses() {
  await client.connect();

  let res = await client.query("SELECT * FROM expenses ORDER BY created_on");

  res.rows.forEach(row => {
    let data = [
      String(row.id).padStart(3),
      row.created_on.toDateString().padStart(10),
      row.amount.padStart(12),
      row.memo
    ];
    
    console.log(data.join(' | '));
  });

  client.end();
}

function displayHelp() {
  console.log(HELP);
}

let args = process.argv;
let command = args[2];

if (command === 'list') {
  listExpenses();
} else {
  displayHelp();
}
